name: SWA - HandyFix Portal

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy (Portal)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PORTAL }} # <-- create this secret
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "apps/handyfix-portal"
          api_location: ""
          output_location: "dist"
        env:
          VITE_API_BASE_URL: "https://rg-handyfix-prod-bngheqdafje9ghhb.westus2-01.azurewebsites.net"

  close_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR (Portal)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PORTAL }}
          action: close
