name: SWA - HandyFix Web

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - "apps/handyfix-web/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy (Web)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_WATER_05F581E1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "apps/handyfix-web"
          api_location: ""
          output_location: "dist"
        env:
          VITE_API_BASE_URL: "https://rg-handyfix-prod-bngheqdafje9ghhb.westus2-01.azurewebsites.net"
          APP_BUILD_COMMAND: "npm ci && npm run build:web"
